### ISSUE TITLE
ValueError: Cannot feed value of shape (8, 10) for Tensor 'source_label:0', which has shape '(?, 4)'

### ISSUE THREAD

**Issue by leokwu** [hujinsen/StarGAN-Voice-Conversion#8]
now ,have this error:
Traceback (most recent call last):
  File "train.py", line 283, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 158, in train
    lambda_classifier=lambda_classifier
  File "/home/wuli/work/deeplearning/tf-star-gan-voice-conversion/StarGAN-Voice-Conversion/model.py", line 148, in train
    self.generator_learning_rate: generator_learning_rate})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (8, 10) for Tensor 'source_label:0', which has shape '(?, 4)'

Have you met this error before?

**Comment by hujinsen** [comment]
change [this value](https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/109563476ac125647232495e0b126b7c41101807/preprocess.py#L14) to 10

**Comment by leokwu** [comment]
Traceback (most recent call last):
  File "train.py", line 283, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 60, in train
    model = StarGANVC(num_features=FEATURE_DIM, frames=FRAMES)
  File "/home/wuli/work/deeplearning/tf-star-gan-voice-conversion/StarGAN-Voice-Conversion/model.py", line 32, in __init__
    self.build_model()
  File "/home/wuli/work/deeplearning/tf-star-gan-voice-conversion/StarGAN-Voice-Conversion/model.py", line 92, in build_model
    self.domain_fake_loss = cross_entropy_loss(self.domain_out_fake, target_label_reshape)
  File "/home/wuli/work/deeplearning/tf-star-gan-voice-conversion/StarGAN-Voice-Conversion/utils.py", line 18, in cross_entropy_loss
    return tf.reduce_mean(tf.losses.softmax_cross_entropy(onehot_labels=labels, logits=logits))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/losses/losses_impl.py", line 737, in softmax_cross_entropy
    logits.get_shape().assert_is_compatible_with(onehot_labels.get_shape())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 844, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?, 1, 1, 4) and (?, 1, 1, 10) are incompatible



It looks like there's some other value that needs to be changed to 10?

**Comment by leokwu** [comment]
Can you help solve this problem together?

tks.

**Comment by leokwu** [comment]
Cut to four train/test data, It works.
